baseurl = "http://iahmed.me/"
title = "Ibrahim Ahmed"
languageCode = "en-us"
theme = "hugolb"
copyright = "Ibrahim Ahmed"

# hugo build parameters
paginate = 12
paginatePath = "p"
ignoreFiles = [".+pptx$"]
# ====

[params]
# Site/Blog/theme specific parameters
# ====
    splashSubheading = "Electrical Engineering @ Vanderbilt University"
    blogroot = "Posts"
    defaultprojimg = "/img/gear.png"

    [[params.links]]
        URL = "https://www.linkedin.com/in/IbrahimAhmed1"
        image = "/img/LinkIcons/svg/linkedin.svg"

    [[params.links]]
        URL = "https://github.com/hazrmard"
        image = "/img/LinkIcons/svg/github.svg"

    [[params.links]]
        URL = "http://stackoverflow.com/users/4591810/hazrmard"
        image = "/img/LinkIcons/svg/stackoverflow.svg"


    [[params.menu.main]]
        name = "Home"
        weight = 0
        url = "/"
        image = "/img/LinkIcons/svg/home.svg"
    [[params.menu.main]]
        name = "About Me"
        weight = 10
        url = "/about/"
        image = "/img/LinkIcons/svg/person.svg"
    [[params.menu.main]]
        name = "Résumé"
        weight = 20
        url = "/resume/"
        image = "/img/LinkIcons/svg/document.svg"
    [[params.menu.main]]
        name = "Posts"
        weight = 30
        url = "/post/"
        image = "/img/LinkIcons/svg/pencil.svg"
    [[params.menu.main]]
        name = "Projects"
        weight = 40
        url = "/project/"
        image = "/img/LinkIcons/svg/terminal.svg"
# ====

# Other hugo configuration options
# ====
[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

# Blackfriday markdown rendering
[blackfriday]
    
